name: PR 템플릿
description: PR 생성 시 이 템플릿을 사용해 주세요.
title: "[PR] "

body:
  - type: input
    id: issue_reference
    attributes:
      label: "#️⃣ 연관된 이슈"
      description: 관련된 이슈 번호를 입력해주세요. 예: #23
      placeholder: "#이슈번호"

  - type: textarea
    id: work_summary
    attributes:
      label: "#️⃣ 작업 내용"
      description: 이번 PR에서 작업한 내용을 간략히 설명해주세요.
      placeholder: |
        - 어떤 기능을 구현했는지
        - 주요 변경사항은 무엇인지
        - 이미지가 있다면 첨부해주세요

  - type: textarea
    id: test_results
    attributes:
      label: "#️⃣ 테스트 결과"
      description: 테스트 수행 결과를 요약해주세요. (예: 테스트 통과 여부 등)
      placeholder: |
        - 모든 테스트 통과
        - 새 테스트 케이스 작성 완료

  - type: checkboxes
    id: change_checklist
    attributes:
      label: "#️⃣ 변경 사항 체크리스트"
      options:
        - label: 코드에 영향이 있는 모든 부분에 대한 테스트를 작성하고 실행했나요?
        - label: 문서를 작성하거나 수정했나요? (필요한 경우)
        - label: 코드 컨벤션에 따라 코드를 작성했나요?
        - label: 본 PR에서 발생할 수 있는 모든 의존성 문제가 해결되었나요?

  - type: textarea
    id: screenshot
    attributes:
      label: "#️⃣ 스크린샷 (선택)"
      description: 관련된 스크린샷이 있다면 첨부해주세요.
      placeholder: |
        예: 기능 동작 화면, 에러 로그 등

  - type: textarea
    id: review_notes
    attributes:
      label: "#️⃣ 리뷰 요구사항 (선택)"
      description: 리뷰어가 중점적으로 봐야 할 부분이 있다면 작성해주세요.
      placeholder: |
        예: 이 부분의 코드 로직 검토 부탁드립니다.

  - type: textarea
    id: reference_links
    attributes:
      label: "📎 참고 자료 (선택)"
      description: 관련 문서, 이슈, 노션 링크 등이 있다면 추가해주세요.
      placeholder: |
        - Notion 문서 링크
        - 관련 RFC
